# Generated by Django 5.0.6 on 2024-06-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceit_ml', '0002_remove_team_text_team_name_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
