# Generated by Django 5.0.6 on 2024-07-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='points',
            new_name='elo',
        ),
    ]
